### ISSUE TITLE
Option to create alternate file if it doesn't exist

### ISSUE THREAD

**Issue by henrik** [tpope/vim-rails#135]
It's a bit of a chore to create the alternate file (typically the spec for a model or helper) if you didn't use a generator.

It would be neat if Rails.vim had some way to do this. Perhaps :A! to jump to alternate file and create it, or prompt to create it, if not there? Or perhaps it should always prompt for that?

An argument against is if you accidentally mix up :R and :A (I do every so often) and it creates files you don't want. But if it would prompt, or would take an exclamation mark, that would probably be good enough. So you do :A, it says "no such file", you do :A! instead.

Similarly for :R, I suppose, to create views.

**Comment by tpope** [comment]
I have enabled an experimental feature to prompt to create an alternate if it doesn't exist if `'confirm'` is set. Currently it has the following limitations:

* Alternate only, not related.
* Doesn't fill in the template.
* Only works for alternates integrated into the projection system.

For that last one, I could use some contributions.  If you want to help, take a look at e6d25365f785b0951be44247329a38051446128b and try to replicate it for some other coherent groups of alternates.

**Comment by tpope** [comment]
I should add that a few types (in particular views) will prove difficult to impossible to add, so don't worry about getting 100%.

**Comment by bootleq** [comment]
I think the prompt-to-create feature is great enough, would you like below ideas, for existing user to enjoy it easier?

1. Not rely on `'confirm'` option. Usually 'confirm' let user to force `:A` to perform its `:A!` counterpart, while in our case it's used like an option "whether to ask to create file if not exist", and is not easy to toggle. Maybe always do prompt is fine.
2. If can't find alternate files from projection, fallback to `rails#buffer().alternate()`.   
This helps since not all alternate were integrated into projection for the time being.

**Comment by tpope** [comment]
Can confirm this seems to be broken.

**Comment by sj26** [comment]
I actually kinda like `:Eunittest ...!`, but is there a way to insert the current "name", like I'm in `app/models/user/email.rb` and I want to create `spec/models/user/email_spec.rb` with the template, can I do something like `Eunittest %!`?

**Comment by tpope** [comment]
The short answer is that current "name" isn't really a singular concept. `:Eunittest user/email` and `:Espec models/user/email` demonstrate two different names for the same thing.

Personally I do just type out `:Euni user/email!` when the need arises, for what it's worth. It doesn't happen *that* often, and I find that has less cognitive load than selecting from a list.

Anyways if anyone wants to bisect to figure out when `:confirm A` broke I can probably fix it without too much trouble.

**Comment by jlahtinen** [comment]
I just upgraded plugin and now `:A` does not automatically create missing spec file. It did it in 
21ada3b19b77fc121afeb233c2b740600e41249a and first breaking commit is 582883d9ca19f92f92ee30145c4aa84b4baec145.

582883d9ca19f92f92ee30145c4aa84b4baec145 is also a culprit for `:confirm A` to not work.

I tested these with multiple other plugins enabled. Should I try again without other plugins?

VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Nov 22 2017 11:38:31)
Included patches: 1-2367

**Comment by tpope** [comment]
Looking a bit closer, it does seem to work for the case where there's a projection for the alternate, which is by design. The thing I forgot is that most stuff in `app/` doesn't implement alternates in terms of projections. It should work the opposite way, creating an `app/` file for something in `spec/`. See if that matches up with your experience.
