### ISSUE TITLE
Bang file creation with different extensions?

### ISSUE THREAD

**Issue by cvincent** [tpope/vim-rails#409]
Right now I can create a new JavaScript file really nicely with `:Ejavascript new_file!`, resulting in a new file at `app/assets/javascripts/new_file.js`. But what if I want, say, a CoffeeScript file at `app/assets/new_file.js.coffee`? Similarly, it would be nice to be able to create SCSS/SASS files with the bang form of `:Estylesheet`.

**Comment by tpope** [comment]
This is hard to do because Rails is so lax in the numerous variations it accepts. `jquery.pluginname.js.coffee.erb` is valid for example, as is `users.coffee`. But if you have `coffee-rails` in your Gemfile and bundler.vim installed, it should do the right thing if no extension is given.

Please feel free to investigate further improvements.
