### ISSUE TITLE
Would you consider adding :Eroutes as a default?

### ISSUE THREAD

**Issue by joallard** [tpope/vim-rails#427]
After trying a few times invoking `:Eroutes` on separate occasions, expecting it to be there, I've been left wondering why you can `:Eschema` but not the routes. I've read #171, #346, but I'm still left wondering why this isn't out-of-the-box. `:Einit...` seems counter-intuitive to me, and following a Ruby philosophy, "things should ideally be where you expect them to be".

My question being: would you consider adding `:Eroutes` as a command present by default?

**Comment by tpope** [comment]
I've been resisting `:Eroutes` just because it'd be a weird one off command that doesn't take an argument. `:Eschema`, on the other hand, has some cleverness that jumps to individual table definitions.

That does suggest the cool idea of a `:Eroutes admin/users` which can jump to `namespace :admin do resource :users`. I think something like that is the only way I'd capitulate.

**Comment by joallard** [comment]
Thanks for the rationale. Food for thought.
