### ISSUE TITLE
Autocomplete is greedier with nested controllers and models than with views

### ISSUE THREAD

**Issue by heironimus** [tpope/vim-rails#513]
Suppose I have the following directory structure:
```
app
  controllers
    users
      employees_controller.rb
      managers_controller.rb
  views
    users
      employees
        show.html.erb
      managers
        show.html.erb
```
When I type `:Econtroller use<tab>` it goes to `:Econtroller users\employees` not `:Econtroller users\`, which is what I expect and how `:Eview` works. For example, `:Eview use<tab>` goes to `:Eview users\` and allows me to continue tabbing or typing. 

`:Emodel` works similarly to `:Econtroller`

tl;dr
`:Eview` autocompletion stops where I expect it to. `:Econtroller` and `:Emodel` go too far, IMHO.

**Comment by tpope** [comment]
Did that intentionally a billion years ago because there are an order of magnitude views than other types, and I like being about to do `:Eco emp<Tab>` or even `:Eco ue<Tab>`. If that's too ambiguous, you can do `:Eco u/e<Tab>`. I'd encourage you to try doing one big tab complete rather than several smaller ones, and see how it feels.

**Comment by heironimus** [comment]
Make sense. The redundant view names also make it reasonable to treat them separately.

`:Eco u/e<Tab>` works great! 👍 for the big tab!

FWIW, `Eco ue` did not work as well as I had hoped in an example more complicated than the one above, but putting the slash in works great. Thanks!
