### ISSUE TITLE
Is Minitest supported "out of the box" like Rspec is?

### ISSUE THREAD

**Issue by leesmith** [tpope/vim-rails#603]
I'm using Minitest in a Rails 7.1 app and I was expecting to be able to call navigation commands like `:Etest models<Tab>` and it work exactly like Rspec navigation commands, `:Espec models<Tab>` but that's not the case. Why is that? I'm seeing [the related test projections in the code](https://github.com/tpope/vim-rails/blob/master/autoload/rails.vim#L4509) but what about my project or setup is preventing them from working? Many thanks!

**Comment by tpope** [comment]
There's no `:Etest`, just `:Eunittest`, `:Efunctionaltest`, etc. This dates back to the days when rails used `test/unit/`, `test/functional/` etc. The commands support the the new directory structure while using the old names. I didn't rename them because having both `:Emodel` and `:Emodeltest` makes tab completion very annoying.

**Comment by tpope** [comment]
I never liked having `:Espec` as a catchall, but given that it exists, `:Etest` would make sense. Though the implementation of `:Espec` has some weird special casing and I'm not sure how that translates: https://github.com/tpope/vim-rails/blob/3a155462d1c346e291595400ca238037d02a357f/autoload/rails.vim#L3330-L3345
