### ISSUE TITLE
add :Rfactory command for test/factories/**/*.rb

### ISSUE THREAD

**Issue by sunaku** [tpope/vim-rails#85]
Please add an `:Rfactory` command that gives quick access to `test/factories/**/*.rb` just like `:Rmodel` gives quick access to `app/model/**/*.rb`.  Thanks!

**Comment by anhari** [comment]
Awesome guys, thank you so much for this.

**Comment by borenho** [comment]
Anyone else who comes here in future (and thanks Tim!) -> https://github.com/christoomey/vim-rfactory

**Comment by tpope** [comment]
`:Efixtures` opens factories now. Spread the word.

**Comment by borenho** [comment]
Thanks Tim! 😻

**Comment by Seybo** [comment]
any substiture to `Efixtures` already? `Efixtures` doesn't seem to work right now

**Comment by tpope** [comment]
It works right now.

**Comment by Seybo** [comment]
it looks into `spec/fixtures/` but my factories (and i suppose it's common) are in `spec/factories`. Maybe there is a simple way to handle it?

**Comment by tpope** [comment]
It looks in both `spec/fixtures` and `spec/factories`.

**Comment by Seybo** [comment]
yeah, my bad. The problem in my case is that my project factories are called like `modelname_factories.rb`

**Comment by tpope** [comment]
It's a bit clumsy but `:Efixtures modelname<Tab>` will still work.

**Comment by Seybo** [comment]
yeah. But can get better with a bit of a vimscript i guess :)
`nmap <Leader>rb viw"sy:Efixtures <C-r>=tolower(substitute(substitute(@s, '\n', '', 'g'), '/', '\\/', 'g'))<cr>`
My first attempt. Can't find a way to pass a tab in the end

**Comment by tpope** [comment]
Tab complete is an interactive way to save typing a few characters. If you're scripting it you could just as well type out the `_factories`.

**Comment by Seybo** [comment]
yeah, but i've noticed that this binding works great for the vcr cassettes. 

Like, I have a line like this in my spec:
`vcr: { cassette_name: 'services/order_service/create' ... `
i visually select the path part
i use this mapping: `vmap <Leader>rb "sy:Efixtures <C-r>=tolower(substitute(substitute(@s, '\n', '', 'g'), '/', '\\/', 'g'))<cr>`
and it works great, i only need to press tab and enter afterwards to open this cassete

so i would prefer to keep this binding universal

**Comment by Seybo** [comment]
`gf` doesn't work in this case because of cassettes `.yml`  extension (it looks for `.rb`). Probably it can be fixed somehow and it would be a better solution

**Comment by tpope** [comment]
This is wandering into the weeds so let me just conclude with a reminder that while FactoryBot will slurp up any `.rb` file in `spec/factories` or `test/factories`, the standard naming scheme - the one used by the generators - is `modelnames.rb`: plural with no suffix other than the file extension. It can optionally be configured to use a suffix like `modelnames_factory.rb`, which rails.vim doesn't support but could. It can only support a singular model name (`modelname_factories.rb`) with custom code. If that's really what you're doing, you're on your own.

> `gf` doesn't work in this case because of cassettes `.yml` extension (it looks for `.rb`). Probably it can be fixed somehow and it would be a better solution

I'm gonna loosen that up a bit so that it doesn't force `.rb` on literal string values by default. That's not enough to make it work in this case, but it might if paired with `:setlocal suffixesadd+=.yml`.
